#########################
# Logging
#########################
logging.level.de.tmosebach.slowen=TRACE

#########################
# MyBatis konfiguration
#########################
mybatis.mapper-locations=classpath:mappings/*.xml
mybatis.configuration.log-impl=org.apache.ibatis.logging.slf4j.Slf4jImpl

#########################
# Datenbank definition
#########################
spring.datasource.url=jdbc:h2:mem:db
