### Events abrufen
GET http://localhost:3000/api/events

### Giro-Konto anlegen
POST http://localhost:3000/api/commands
Content-Type: application/json

{
  "commandType": "erstelleKonto",
  "kontoType" : "Konto",
  "name": "ING-Giro",
  "bilanzType": "Bestand"
}

### Tagesgeld-Konto anlegen
POST http://localhost:3000/api/commands
Content-Type: application/json

{
  "commandType": "erstelleKonto",
  "kontoType" : "Konto",
  "name": "ING-Extra",
  "bilanzType": "Bestand"
}

### Buchung

POST http://localhost:3000/api/commands HTTP/1.1
Content-Type: application/json

{
  "commandType": "buche",
  "verwendung": "Verwendung",
  "empfaenger": "ich",
  "umsaetze": [
    {
      "konto": "ING-Giro",
      "valuta": "2022-12-27",
      "betrag": {
        "wert": -243.42,
        "waehrung": "EUR"
      }
    },
    {
      "konto": "ING-Extra",
      "valuta": "2022-12-27",
      "betrag": {
        "wert": 243.42,
        "waehrung": "EUR"
      }
    }
  ]
}

### Hauptbuch abfragen
GET http://localhost:3000/api/views/hauptbuch

### Asset erstellen

POST http://localhost:3000/api/commands
Content-Type: application/json

{
  "commandType" : "erstelleAsset",
  "isin" : "DE0005933956",
  "wkn" : "593395",
  "assetType" : "ETF",
  "name" : "iShare Core EURO STOCC 50 UCITS ETF (DE)"
}

### Liste der Assets abfragen
GET http://localhost:3000/api/views/assets
