### Events abrufen
GET http://localhost:3000/api/events

### Commands absetzen
POST http://localhost:3000/api/commands
Content-Type: application/json

{
  "commandType": "erstelleKonto",
  "kontoType" : "Konto",
  "name": "ING-Giro",
  "bilanzType": "Bestand"
}

### Hauptbuch abfragen
GET http://localhost:3000/api/views/hauptbuch

### 
