INSERT INTO KONTO ( NAME, ART, BILANZPOSITION, WAEHRUNG ) VALUES ('Giro', 'Konto', 'Kontokorrent', 'EUR');
INSERT INTO KONTO ( NAME, ART, BILANZPOSITION, WAEHRUNG ) VALUES ('Tagesgeld', 'Konto', 'Aktiv', 'EUR');
INSERT INTO KONTO ( NAME, ART, BILANZPOSITION, WAEHRUNG ) VALUES ('Konto', 'Konto', 'Aktiv', 'EUR');
INSERT INTO KONTO ( NAME, ART, BILANZPOSITION, WAEHRUNG ) VALUES ('Stückzins', 'Konto', 'Aufwand', 'EUR');
INSERT INTO KONTO ( NAME, ART, BILANZPOSITION, WAEHRUNG ) VALUES ('Provision', 'Konto', 'Aufwand', 'EUR');
INSERT INTO KONTO ( NAME, ART, BILANZPOSITION ) VALUES ('Depot', 'Depot', 'Aktiv');