#########################
# Logging
#########################
logging.level.de.tmosebach.slowen=TRACE

#########################
# MyBatis konfiguration
#########################

# Mappings aus allen Jars auf dem Classpath übernehmen
mybatis.mapper-locations=classpath*:mappings/*.xml
mybatis.configuration.log-impl=org.apache.ibatis.logging.slf4j.Slf4jImpl
