/**
 * Basiskonten anlegen
 */

drop table if exists buchung CASCADE;
create table buchung (
	id bigint generated by default as identity, 
	empfaenger varchar(40), 
	verwendung varchar(40), 
	primary key (id)
);

drop table if exists konto CASCADE;
create table konto (
	konto_type varchar(1) not null,
	id bigint generated by default as identity,
	art varchar(15), 
	name varchar(30),
	saldo decimal(19,2),
	primary key (id)
);
alter table konto add constraint UK_14tpvl6e0sv3u0wd6fujxhscu unique (name);

drop table if exists konto_umsatz CASCADE;
create table konto_umsatz (
	umsatz_type varchar(31) not null,
	id bigint generated by default as identity,
	betrag decimal(19,2) not null,
	valuta date not null,
	buchung_id bigint not null,
	konto_id bigint not null,
	primary key (id)
);
alter table konto_umsatz add constraint FKfkgdcty1jgmdnig2j9me6ie86 foreign key (buchung_id) references buchung;
alter table konto_umsatz add constraint FKiwjvwrcih5g4fkymakm6u02b9 foreign key (konto_id) references konto;
