create table asset (
	id bigint generated by default as identity,
	isin varchar(255),
	name varchar(255),
	wkn varchar(255), 
	primary key (id)
);

create table bestand (
	id bigint generated by default as identity,
	depot_id bigint not null,
	asset_id bigint not null,
	kauf_preis decimal(19,2) not null,
	stuecke decimal(19,2) not null,
	primary key (id)
);
alter table bestand add constraint depot_constraint foreign key (depot_id) references konto;

ALTER TABLE konto_umsatz 
ADD COLUMN stuecke decimal(19,2);
