DROP TABLE IF EXISTS KONTO;
CREATE TABLE KONTO (
	NAME VARCHAR(255) NOT NULL PRIMARY KEY,
	ART VARCHAR(5) NOT NULL,
	BILANZPOSITION VARCHAR(255) NOT NULL,
	WAEHRUNG VARCHAR(3)
);


DROP TABLE IF EXISTS BUCHUNG;
CREATE TABLE BUCHUNG (
	ID VARCHAR(36) PRIMARY KEY,
	VORGANG VARCHAR(30) NOT NULL,
	DATUM DATE NOT NULL,
	EMPFAENGER VARCHAR(255),
	VERWENDUNG VARCHAR(255)
);


DROP TABLE IF EXISTS UMSATZ;
CREATE TABLE UMSATZ (
	ART VARCHAR(5) NOT NULL,
	BUCHUNG_ID VARCHAR(36) NOT NULL,
	KONTO_ID VARCHAR(255) NOT NULL,
	VALUTA DATE NOT NULL,
	BETRAG DECIMAL(12,2) NOT NULL,
	MENGE DECIMAL(16, 6),
	ASSET_ID VARCHAR(30)
);

/*
DROP TABLE IF EXISTS ASSET;
CREATE TABLE ASSET (
    ID VARCHAR(40) NOT NULL PRIMARY KEY,
	ISIN VARCHAR(20),
	WPK VARCHAR(20),
	NAME VARCHAR(255) NOT NULL,
	TYP VARCHAR(20) NOT NULL
);

DROP TABLE IF EXISTS BESTAND;
CREATE TABLE BESTAND (
    DEPOT_ID VARCHAR(40) NOT NULL,
	ASSET_ID VARCHAR(40),
	MENGE DECIMAL(16,6),
	EINSTAND DECIMAL(12,2) NOT NULL
);
*/
