DROP TABLE IF EXISTS KONTO;
CREATE TABLE KONTO (
	NAME VARCHAR(255) NOT NULL PRIMARY KEY,
	ART VARCHAR(255) NOT NULL,
	BILANZPOSITION VARCHAR(255) NOT NULL,
	WAEHRUNG VARCHAR(3)
);

/*
DROP TABLE IF EXISTS BUCHUNG;
CREATE TABLE BUCHUNG (
	ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	DATUM DATE NOT NULL,
	EMPFAENGER VARCHAR(255),
	VERWENDUNG VARCHAR(255)
);

DROP TABLE IF EXISTS UMSATZ;
CREATE TABLE UMSATZ (
	BUCHUNG_ID INT NOT NULL,
	KONTO_ID VARCHAR(40) NOT NULL,
	TYP VARCHAR(11),
	VALUTA DATE NOT NULL,
	BETRAG DECIMAL(12,2) NOT NULL,
	MENGE DECIMAL(16, 6),
	ASSET_ID INT
);

DROP TABLE IF EXISTS ASSET;
CREATE TABLE ASSET (
    ID VARCHAR(40) NOT NULL PRIMARY KEY,
	ISIN VARCHAR(20),
	WPK VARCHAR(20),
	NAME VARCHAR(255) NOT NULL,
	TYP VARCHAR(20) NOT NULL
);

DROP TABLE IF EXISTS BESTAND;
CREATE TABLE BESTAND (
    DEPOT_ID VARCHAR(40) NOT NULL,
	ASSET_ID VARCHAR(40),
	MENGE DECIMAL(16,6),
	EINSTAND DECIMAL(12,2) NOT NULL
);
*/
